framework:
    default_locale: en
    translator:
        enabled: false #pour désactiver les messages d'erreur dans la debug bar !
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
